services:
  # PostgreSQL Database
  - type: pserv
    name: freeresumebuilder-db
    plan: free
    region: oregon
    databaseName: freeresumebuilder
    user: freeresumebuilder

  # MinIO Storage Service (using Redis for simplicity on free tier)
  - type: redis
    name: freeresumebuilder-storage
    plan: free
    region: oregon

  # Backend API Server
  - type: web
    name: freeresumebuilder-backend
    plan: free
    region: oregon
    runtime: node
    buildCommand: |
      echo "Installing dependencies..."
      npm install -g pnpm
      pnpm install
      echo "Generating Prisma client..."
      pnpm prisma:generate
      echo "Building backend..."
      pnpm nx build server
    startCommand: |
      echo "Running database migrations..."
      pnpm prisma:migrate
      echo "Starting backend server..."
      pnpm start
    envVars:
      # Basic Configuration
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      
      # URLs (will be updated after deployment)
      - key: PUBLIC_URL
        value: https://freeresumebuilder.onrender.com
      - key: STORAGE_URL
        value: https://freeresumebuilder-backend.onrender.com/storage
      
      # Database (PostgreSQL)
      - key: DATABASE_URL
        fromDatabase:
          name: freeresumebuilder-db
          property: connectionString
      
      # Authentication Secrets
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET  
        generateValue: true
      
      # Email Configuration
      - key: MAIL_FROM
        value: noreply@freeresumebuilder.co
      
      # Storage Configuration (using filesystem for free tier)
      - key: STORAGE_ENDPOINT
        value: localhost
      - key: STORAGE_PORT
        value: 9000
      - key: STORAGE_REGION
        value: us-east-1
      - key: STORAGE_BUCKET
        value: default
      - key: STORAGE_ACCESS_KEY
        value: minioadmin
      - key: STORAGE_SECRET_KEY
        value: minioadmin
      - key: STORAGE_USE_SSL
        value: "false"
      - key: STORAGE_SKIP_BUCKET_CHECK
        value: "true"
      
      # Feature Flags (disable auth as per requirements)
      - key: DISABLE_SIGNUPS
        value: "true"
      - key: DISABLE_EMAIL_AUTH
        value: "true"
      
      # PDF Generation (using built-in for free tier)
      - key: CHROME_TOKEN
        value: chrome_token
      - key: CHROME_URL
        value: ws://localhost:3000

  # Frontend React App
  - type: web
    name: freeresumebuilder-frontend
    plan: free
    region: oregon
    runtime: node
    buildCommand: |
      echo "Installing dependencies..."
      npm install -g pnpm
      pnpm install
      echo "Building frontend..."
      pnpm nx build client
    startCommand: |
      echo "Serving frontend..."
      npx serve -s dist/apps/client -l 3000
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SERVER_URL
        value: https://freeresumebuilder-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Build and deployment configuration
buildCommand: |
  echo "Installing global dependencies..."
  npm install -g pnpm nx
  echo "Installing project dependencies..."
  pnpm install
  echo "Generating Prisma client..."
  pnpm prisma:generate

# Environment variables that apply to all services
envVars:
  - key: PNPM_VERSION
    value: "8.15.0"
  - key: NODE_VERSION
    value: "22.13.1"